export enum ActionTypes {
  LOAD_ACTIVITIES = 'LOAD_ACTIVITIES',
  LOAD_ACTIVITY = 'LOAD_ACTIVITY',
  CREATE_ACTIVITY = 'CREATE_ACTIVITY',
  UPDATE_ACTIVITY = 'UPDATE_ACTIVITY',
  DELETE_ACTIVITY = 'DELETE_ACTIVITY',
}
